-- SavingBuddy initial schema.
--
-- Enum-backed columns are plain varchar with a check constraint rather than a
-- native H2 enum: adding a value stays a data concern instead of a DDL one, and
-- the schema ports to PostgreSQL unchanged.
-- Money is numeric(14,2) everywhere — never a floating-point type.

create table accounts (
    id         bigint generated by default as identity primary key,
    code       varchar(8) not null,
    name       varchar(255) not null,
    kind       varchar(16) not null,
    balance    numeric(14,2) not null,
    sort_order integer not null,
    constraint ck_accounts_kind check (kind in ('BILLS', 'SAVINGS', 'SPENDING'))
);

create table plan (
    id                  bigint generated by default as identity primary key,
    owner_name          varchar(255) not null,
    employer            varchar(255) not null,
    payday              integer not null,
    salary              numeric(14,2) not null,
    bills_allocation    numeric(14,2) not null,
    savings_target      numeric(14,2) not null,
    spending_allowance  numeric(14,2) not null
);

create table transactions (
    id          bigint generated by default as identity primary key,
    account_id  bigint not null,
    name        varchar(255) not null,
    category    varchar(255) not null,
    kind        varchar(16) not null,
    amount      numeric(14,2) not null,
    occurred_at timestamp(6) not null,
    note        varchar(255),
    constraint fk_transactions_account foreign key (account_id) references accounts (id),
    constraint ck_transactions_kind check (kind in ('SPENDING', 'BILL', 'INCOME'))
);

-- The month-range scan behind Safe to Spend runs on every read.
create index ix_transactions_occurred_at on transactions (occurred_at);
create index ix_transactions_account on transactions (account_id);

create table bills (
    id           bigint generated by default as identity primary key,
    account_id   bigint not null,
    name         varchar(255) not null,
    amount       numeric(14,2) not null,
    due_day      integer not null,
    method       varchar(16) not null,
    last_paid_on date,
    constraint fk_bills_account foreign key (account_id) references accounts (id),
    constraint ck_bills_method check (method in ('AUTO_DEBIT', 'MANUAL', 'VARIES')),
    constraint ck_bills_due_day check (due_day between 1 and 31)
);

create index ix_bills_due_day on bills (due_day);

create table goals (
    id           bigint generated by default as identity primary key,
    name         varchar(255) not null,
    description  varchar(255),
    target       numeric(14,2) not null,
    saved        numeric(14,2) not null,
    monthly      numeric(14,2) not null,
    target_month varchar(7) not null,
    priority     boolean not null,
    delay_months integer not null,
    sort_order   integer not null
);

-- Closed-month history. "period" rather than "month" — the latter is reserved.
create table month_summaries (
    id         bigint generated by default as identity primary key,
    period     varchar(7) not null unique,
    income     numeric(14,2) not null,
    saved      numeric(14,2) not null,
    eating_out numeric(14,2) not null,
    groceries  numeric(14,2) not null,
    transport  numeric(14,2) not null,
    other      numeric(14,2) not null
);

create table observations (
    id         bigint generated by default as identity primary key,
    title      varchar(255) not null,
    body       varchar(500) not null,
    tone       varchar(8) not null,
    sort_order integer not null,
    constraint ck_observations_tone check (tone in ('WARN', 'GOOD'))
);

create table saving_plans (
    id            bigint generated by default as identity primary key,
    total_amount  numeric(14,2) not null,
    weeks         integer not null,
    weekly_amount numeric(14,2) not null,
    created_at    timestamp(6) not null
);
