-- Multi-user: every row belongs to a user.
--
-- An existing single-user install is adopted, not abandoned: its data is
-- assigned to a user created from the current plan (email owner@localhost,
-- password "savingbuddy" — documented in the README with instructions to
-- change it). A fresh database gets no user here; registration creates one.

create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null,
    password_hash varchar(100) not null,
    created_at    timestamp(6) not null,
    constraint uq_users_email unique (email)
);

insert into users (email, password_hash, created_at)
select 'owner@localhost', '$2y$10$lpK4WafF7ly3cwisBYGI5.Uunz0ZE7HkTGUoqzMxBDEyXSXMJJiQG', current_timestamp
where exists (select 1 from plan);

-- plan: one per user, not one per database.
alter table plan add column user_id bigint;
update plan set user_id = (select min(id) from users);
alter table plan alter column user_id set not null;
alter table plan add constraint fk_plan_user foreign key (user_id) references users (id);
alter table plan add constraint uq_plan_user unique (user_id);

alter table accounts add column user_id bigint;
update accounts set user_id = (select min(id) from users);
alter table accounts alter column user_id set not null;
alter table accounts add constraint fk_accounts_user foreign key (user_id) references users (id);
create index ix_accounts_user on accounts (user_id);

alter table transactions add column user_id bigint;
update transactions set user_id = (select min(id) from users);
alter table transactions alter column user_id set not null;
alter table transactions add constraint fk_transactions_user foreign key (user_id) references users (id);
-- Replaces the plain occurred_at index for the month-range scan, now always user-scoped.
create index ix_transactions_user_occurred on transactions (user_id, occurred_at);

alter table bills add column user_id bigint;
update bills set user_id = (select min(id) from users);
alter table bills alter column user_id set not null;
alter table bills add constraint fk_bills_user foreign key (user_id) references users (id);
create index ix_bills_user on bills (user_id);

alter table goals add column user_id bigint;
update goals set user_id = (select min(id) from users);
alter table goals alter column user_id set not null;
alter table goals add constraint fk_goals_user foreign key (user_id) references users (id);
create index ix_goals_user on goals (user_id);

alter table observations add column user_id bigint;
update observations set user_id = (select min(id) from users);
alter table observations alter column user_id set not null;
alter table observations add constraint fk_observations_user foreign key (user_id) references users (id);
create index ix_observations_user on observations (user_id);

alter table saving_plans add column user_id bigint;
update saving_plans set user_id = (select min(id) from users);
alter table saving_plans alter column user_id set not null;
alter table saving_plans add constraint fk_saving_plans_user foreign key (user_id) references users (id);
create index ix_saving_plans_user on saving_plans (user_id);

-- month_summaries is rebuilt rather than altered: V1 declared unique(period)
-- inline, so its constraint name is database-generated and cannot be dropped
-- portably — and "one row per month" must become "one row per user per month".
alter table month_summaries rename to month_summaries_old;

create table month_summaries (
    id         bigint generated by default as identity primary key,
    user_id    bigint not null,
    period     varchar(7) not null,
    income     numeric(14,2) not null,
    saved      numeric(14,2) not null,
    eating_out numeric(14,2) not null,
    groceries  numeric(14,2) not null,
    transport  numeric(14,2) not null,
    other      numeric(14,2) not null,
    constraint fk_month_summaries_user foreign key (user_id) references users (id),
    constraint uq_month_summaries_user_period unique (user_id, period)
);

insert into month_summaries (user_id, period, income, saved, eating_out, groceries, transport, other)
select (select min(id) from users), period, income, saved, eating_out, groceries, transport, other
from month_summaries_old;

drop table month_summaries_old;
