-- In-app invitations, so letting someone register is a product action rather
-- than an environment-variable change and a redeploy.
--
-- The token is never stored. Only its SHA-256 hex digest is, so a database dump
-- or a stray query result does not hand anyone a working invite.

create table invites (
    id                  bigint generated by default as identity primary key,
    token_hash          varchar(64) not null,
    created_by_user_id  bigint not null,
    created_at          timestamp(6) not null,
    expires_at          timestamp(6) not null,
    used_at             timestamp(6),
    used_by_user_id     bigint,
    constraint uq_invites_token_hash unique (token_hash),
    constraint fk_invites_created_by foreign key (created_by_user_id) references users (id),
    constraint fk_invites_used_by foreign key (used_by_user_id) references users (id),
    -- used_at and used_by_user_id are set together or not at all.
    constraint ck_invites_used_consistent check (
        (used_at is null and used_by_user_id is null)
        or (used_at is not null and used_by_user_id is not null)
    )
);

-- Registration looks an invite up by hash on every attempt; the unique
-- constraint already indexes it. This one serves the owner's "my invites" list.
create index ix_invites_created_by on invites (created_by_user_id, created_at desc);
