-- Registration mode moves from an environment variable into the database, so
-- admitting people is a product action rather than a redeploy.
--
-- The env var still seeds the first value and still acts as the fallback when no
-- row exists, which keeps a fresh deployment fail-closed.

create table app_settings (
    id                bigint generated by default as identity primary key,
    registration_mode varchar(16) not null,
    updated_at        timestamp(6) not null,
    -- `open` is deliberately absent: it is only meaningful for a loopback-bound
    -- local instance, and must not be reachable from a deployed UI.
    constraint ck_app_settings_registration_mode check (registration_mode in ('CLOSED', 'INVITE')),
    -- One row, enforced rather than assumed.
    constraint ck_app_settings_singleton check (id = 1)
);
