-- Owner-mediated password reset.
--
-- No email provider: a bare *.onrender.com sender cannot publish SPF/DKIM for a
-- domain it does not own, so the one message that matters most — to someone
-- already locked out — would silently land in spam. Instead the person who
-- invited an account can mint a single-use code for it and hand it over
-- out-of-band, exactly as invites already work.
--
-- Only the SHA-256 digest is stored, so a database dump yields no usable code.

create table password_resets (
    id                 bigint generated by default as identity primary key,
    token_hash         varchar(64) not null,
    target_user_id     bigint not null,
    created_by_user_id bigint not null,
    created_at         timestamp(6) not null,
    expires_at         timestamp(6) not null,
    used_at            timestamp(6),
    constraint uq_password_resets_token_hash unique (token_hash),
    constraint fk_password_resets_target foreign key (target_user_id) references users (id),
    constraint fk_password_resets_creator foreign key (created_by_user_id) references users (id),
    -- Minting for yourself would set a new password without knowing the old one,
    -- bypassing the current-password check on /api/auth/password.
    constraint ck_password_resets_not_self check (target_user_id <> created_by_user_id)
);

-- Minting supersedes any outstanding code for the same account, so this is read
-- on every mint as well as on every claim.
create index ix_password_resets_target on password_resets (target_user_id, used_at);
