/**
 * Money as integer minor units (sen). Ported from the backend's Money.java, and
 * verified against golden values generated by that Java code.
 *
 * Why integers rather than plain numbers: the divergences are interior to the
 * arithmetic, so rounding at the edges does not save you. Real cases from this
 * app, all reproduced:
 *
 *   RM150.15 / RM50.05/mo  -> 3.0000000000000004 in doubles, so Math.ceil gives 4
 *                             where BigDecimal gives 3. That is delayFor(), which
 *                             decides how many months a purchase pushes a goal
 *                             back — and the result is persisted.
 *   Math.round(1.005 * 100) -> 100, because 1.005 is stored as 1.00499999...
 *                             Java HALF_UP gives 1.01.
 *   142.6 * 7               -> 998.1999999999999 rather than 998.20.
 *
 * Every value below 2^53 adds, subtracts and multiplies exactly as an integer,
 * and the widest intermediate here (ratio's part * 10000) is ~1e14 against
 * MAX_SAFE_INTEGER of ~9e15.
 */

/** An amount in sen. Always an integer. */
export type Cents = number

/** Java: BigDecimal.ZERO.setScale(2) */
export const ZERO: Cents = 0

/**
 * Decimal ringgit to sen, for values ALREADY inside the system.
 *
 * Rounds half away from zero, matching Java's HALF_UP — Math.round alone breaks
 * ties toward +Infinity, so Math.round(-0.5) is -0 where Java gives -1.
 *
 * Note what this cannot do: recover the decimal a user typed. 1.005 as a double
 * genuinely IS 1.00499999999999989, so this returns 100 where Java's
 * new BigDecimal("1.005") gives 101. That is not a defect here — the
 * information was lost before this function was called. Parse user input with
 * parseCents instead, which reads the string the way BigDecimal does.
 */
export function toCents(ringgit: number): Cents {
  if (!Number.isFinite(ringgit)) return 0
  const sign = ringgit < 0 ? -1 : 1
  return sign * Math.round(Math.abs(ringgit) * 100)
}

/**
 * Parses a typed amount straight to sen, without ever forming a double.
 *
 * This is the faithful equivalent of new BigDecimal("1.005").setScale(2,
 * HALF_UP): the digits are read as text, so "1.005" rounds to 101 rather than
 * to 100. Every amount in this app arrives as a string from a text field, so
 * this — not toCents — is the real input boundary.
 */
export function parseCents(raw: string): Cents {
  const text = (raw ?? '').trim()
  const match = /^(-?)(\d*)(?:\.(\d*))?$/.exec(text)
  if (!match || (match[2] === '' && (match[3] ?? '') === '')) return 0

  const [, sign, whole, fraction = ''] = match
  const digits = fraction.padEnd(3, '0')
  let cents = Number(whole || '0') * 100 + Number(digits.slice(0, 2))

  // Round half up on the third digit, using the character rather than any
  // arithmetic on a fractional value.
  if (digits.charCodeAt(2) >= '5'.charCodeAt(0)) cents += 1

  return sign === '-' ? -cents : cents
}

/** Sen back to decimal ringgit, for display and for the export bundle. */
export function toRinggit(cents: Cents): number {
  return cents / 100
}

/** Java: Money.floorZero — never show a negative where it would mislead. */
export function floorZero(cents: Cents): Cents {
  return Math.max(0, cents)
}

/**
 * Java: Money.divide — scale 2, RoundingMode.DOWN, with a by <= 0 guard.
 *
 * DOWN, not HALF_UP, and deliberately so: this produces the daily allowance and
 * the weekly Wait & Save amount. Rounding up would tell the user they can spend
 * money they do not have. A port reaching for Math.round here is wrong half the
 * time, and wrong in the direction that costs the user.
 */
export function divide(cents: Cents, by: number): Cents {
  if (by <= 0) return cents
  return Math.trunc(cents / by)
}

/**
 * Java: Money.ratio — scale 4, HALF_UP, 0 when the whole is not positive.
 *
 * Returns a plain number on purpose: it feeds progress bars, and 4dp of a ratio
 * is not money.
 */
export function ratio(part: Cents, whole: Cents): number {
  if (whole <= 0) return 0
  return Math.round((part * 10000) / whole) / 10000
}

/**
 * Java: divide(x, y, 0, RoundingMode.CEILING) — months of contributions still
 * needed, and the months a purchase delays a goal.
 *
 * Exact only because both operands are integers: a quotient whose true value is
 * a whole number comes back exactly, so ceil does not overshoot.
 */
export function ceilDivide(cents: Cents, by: Cents): number {
  if (by <= 0) return 0
  return Math.ceil(cents / by)
}

/** Sums exactly — integer addition below 2^53 cannot drift. */
export function sum(values: Cents[]): Cents {
  return values.reduce((a, b) => a + b, 0)
}
